### PR TITLE
Implement `node`, `nodes`, `allchannels`, and `allupdates` commands

### PR DESCRIPTION
**Pull request by claddyk**
All the command given under [Network section](https://acinq.github.io/eclair/#network) of eclair API Documentation are implemented in this PR. 
The logs (just for reference are given below in comments)

### CODE REVIEW

**Comment by claddyk** [comment]
Logs for `nodes` command:
```
claddy@claddy:~/Documents/eclair-cli$ eclair-cli.kexe nodes -p password --nodeIds 02f666711319435b7905dd77d10c269d8d50c02668b975f526577167d370b50a3e,03c5b161c16e9f8ef3f3bccfb74a6e9a3b423dd41fe2848174b7209f1c2ea25dad
[
    {
        "signature": "127738303268eb708888f2c9f94cfc073fc25eb01ea9c73da556d8fe1627a99315750c567ec52fcf7f3391b30ec7c8168bc6c8f2f136a9e82383ec49f42c61e2",
        "features": {
            "activated": {
                "gossip_queries_ex": "optional",
                "option_data_loss_protect": "optional",
                "var_onion_optin": "mandatory",
                "option_static_remotekey": "optional",
                "option_scid_alias": "optional",
                "option_onion_messages": "optional",
                "option_support_large_channel": "optional",
                "option_anchors_zero_fee_htlc_tx": "optional",
                "payment_secret": "mandatory",
                "option_shutdown_anysegwit": "optional",
                "option_channel_type": "optional",
                "basic_mpp": "optional",
                "gossip_queries": "optional"
            },
            "unknown": [
            ]
        },
        "timestamp": {
            "iso": "2023-08-14T13:21:10Z",
            "unix": 1692019270
        },
        "nodeId": "03c5b161c16e9f8ef3f3bccfb74a6e9a3b423dd41fe2848174b7209f1c2ea25dad",
        "rgbColor": "#49daaa",
        "alias": "alice",
        "addresses": [
        ],
        "tlvStream": {
        }
    },
    {
        "signature": "224aed3776eecb6e9cb1ff232a0e812a427490bac08724f4eeaccc9beaddb8c31490bdf547b779aa278212c847814140709400ccdd32692663bba7ebc56ff030",
        "features": {
            "activated": {
                "gossip_queries_ex": "optional",
                "option_data_loss_protect": "optional",
                "var_onion_optin": "mandatory",
                "option_static_remotekey": "optional",
                "option_scid_alias": "optional",
                "option_onion_messages": "optional",
                "option_support_large_channel": "optional",
                "option_anchors_zero_fee_htlc_tx": "optional",
                "payment_secret": "mandatory",
                "option_shutdown_anysegwit": "optional",
                "option_channel_type": "optional",
                "basic_mpp": "optional",
                "gossip_queries": "optional"
            },
            "unknown": [
            ]
        },
        "timestamp": {
            "iso": "2023-08-14T13:21:10Z",
            "unix": 1692019270
        },
        "nodeId": "02f666711319435b7905dd77d10c269d8d50c02668b975f526577167d370b50a3e",
        "rgbColor": "#49daaa",
        "alias": "bob",
        "addresses": [
        ],
        "tlvStream": {
        }
    }
]
```

**Comment by claddyk** [comment]
Log for the `node` command:
```
claddy@claddy:~/Documents/eclair-cli$ eclair-cli.kexe node -p password --nodeId 02f666711319435b7905dd77d10c269d8d50c02668b975f526577167d370b50a3e
{
  "type": "types.NodeCommandResponse",
  "announcement": {
    "signature": "224aed3776eecb6e9cb1ff232a0e812a427490bac08724f4eeaccc9beaddb8c31490bdf547b779aa278212c847814140709400ccdd32692663bba7ebc56ff030",
    "features": {
      "activated": {
        "gossip_queries_ex": "optional",
        "option_data_loss_protect": "optional",
        "var_onion_optin": "mandatory",
        "option_static_remotekey": "optional",
        "option_scid_alias": "optional",
        "option_onion_messages": "optional",
        "option_support_large_channel": "optional",
        "option_anchors_zero_fee_htlc_tx": "optional",
        "payment_secret": "mandatory",
        "option_shutdown_anysegwit": "optional",
        "option_channel_type": "optional",
        "basic_mpp": "optional",
        "gossip_queries": "optional"
      },
      "unknown": [
      ]
    },
    "timestamp": {
      "iso": "2023-08-14T13:21:10Z",
      "unix": 1692019270
    },
    "nodeId": "02f666711319435b7905dd77d10c269d8d50c02668b975f526577167d370b50a3e",
    "rgbColor": "#49daaa",
    "alias": "bob",
    "addresses": [
    ],
    "tlvStream": {
    }
  }
}
```

**Comment by claddyk** [comment]
Logs for `allupdates` command:
```
claddy@claddy:~/Documents/eclair-cli$ eclair-cli.kexe allupdates -p password --nodeId 03c5b161c16e9f8ef3f3bccfb74a6e9a3b423dd41fe2848174b7209f1c2ea25dad
[
    {
        "signature": "583e402476e4ffedab752fddba502492cf1f6773ed5b989ba75cc0046184200909f8ea18a5c36497504c7c0f2318ce011a43a6990ac22c78c981a4330e2bb6d8",
        "chainHash": "06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f",
        "shortChannelId": "151x2x0",
        "timestamp": {
            "iso": "2023-08-12T12:16:57Z",
            "unix": 1691842617
        },
        "messageFlags": {
            "dontForward": false
        },
        "channelFlags": {
            "isEnabled": true,
            "isNode1": false
        },
        "cltvExpiryDelta": 144,
        "htlcMinimumMsat": 1,
        "feeBaseMsat": 7856,
        "feeProportionalMillionths": 5679,
        "htlcMaximumMsat": 45000000,
        "tlvStream": {
        }
    },
    {
        "signature": "615fab66837d37f0fe9a949b97a6fadd37d42dcfd9adf325a7820880ca195666485d811dc00cdc2f11f98691500a88f77d4eb5179e35f594e7e68e3be71dc8ac",
        "chainHash": "06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f",
        "shortChannelId": "151x3x0",
        "timestamp": {
            "iso": "2023-08-12T12:16:57Z",
            "unix": 1691842617
        },
        "messageFlags": {
            "dontForward": false
        },
        "channelFlags": {
            "isEnabled": true,
            "isNode1": false
        },
        "cltvExpiryDelta": 144,
        "htlcMinimumMsat": 1,
        "feeBaseMsat": 7856,
        "feeProportionalMillionths": 5679,
        "htlcMaximumMsat": 45000000,
        "tlvStream": {
        }
    },
    {
        "signature": "cb57db6ef1cb829eb11cdfd2ad32a0a295a507002282623784d88b9b0266f01e548927b3c1b5b71c3a0b225207efb6ee6d1ac7d23d2daa22f20726cfa58eae16",
        "chainHash": "06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f",
        "shortChannelId": "252x1x1",
        "timestamp": {
            "iso": "2023-08-12T12:16:57Z",
            "unix": 1691842617
        },
        "messageFlags": {
            "dontForward": false
        },
        "channelFlags": {
            "isEnabled": true,
            "isNode1": false
        },
        "cltvExpiryDelta": 144,
        "htlcMinimumMsat": 1,
        "feeBaseMsat": 7856,
        "feeProportionalMillionths": 5679,
        "htlcMaximumMsat": 45000000,
        "tlvStream": {
        }
    },
    {
        "signature": "4d9a50fdfb3d76ce47e26f75440295e1ecde91c1a67e14930bf657c5084e07b6403b0b8047d68c2b2bd765b27a3dc71fd434431881b7d863cf3283496f80bf24",
        "chainHash": "06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f",
        "shortChannelId": "252x2x1",
        "timestamp": {
            "iso": "2023-08-12T12:16:57Z",
            "unix": 1691842617
        },
        "messageFlags": {
            "dontForward": false
        },
        "channelFlags": {
            "isEnabled": true,
            "isNode1": false
        },
        "cltvExpiryDelta": 144,
        "htlcMinimumMsat": 1,
        "feeBaseMsat": 7856,
        "feeProportionalMillionths": 5679,
        "htlcMaximumMsat": 45000000,
        "tlvStream": {
        }
    },
    {
        "signature": "5d0b0155259727236f77947c87b30849ad7209dd17c6cd3ef5e53783df4ca9da4f53c2f9b687c6fc99f4c4bc8bfd7d2c719003c0fbd9b475b0e5978155716878",
        "chainHash": "06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f",
        "shortChannelId": "354x1x1",
        "timestamp": {
            "iso": "2023-08-12T12:16:57Z",
            "unix": 1691842617
        },
        "messageFlags": {
            "dontForward": false
        },
        "channelFlags": {
            "isEnabled": true,
            "isNode1": false
        },
        "cltvExpiryDelta": 144,
        "htlcMinimumMsat": 1,
        "feeBaseMsat": 7856,
        "feeProportionalMillionths": 5679,
        "htlcMaximumMsat": 45000000,
        "tlvStream": {
        }
    },
    {
        "signature": "298b1fa9b4b5104e2826fb1b6687fdebe286b68dc0eef770269bbbcb8569ce28727f001a3a9f70b5d9dce3bc13427ad45359f0d29b03335bc595942e274a753d",
        "chainHash": "06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f",
        "shortChannelId": "354x2x0",
        "timestamp": {
            "iso": "2023-08-12T12:16:57Z",
            "unix": 1691842617
        },
        "messageFlags": {
            "dontForward": false
        },
        "channelFlags": {
            "isEnabled": true,
            "isNode1": false
        },
        "cltvExpiryDelta": 144,
        "htlcMinimumMsat": 1,
        "feeBaseMsat": 7856,
        "feeProportionalMillionths": 5679,
        "htlcMaximumMsat": 45000000,
        "tlvStream": {
        }
    },
    {
        "signature": "38c34b618e4c4458c77354837db2cdbdbfbd647f981aef834aa6dcc65b65087d0dcf538f735bba6c30cefa14f03c511d79af35ca3bb5f90e4f91bfc6a6d3659c",
        "chainHash": "06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f",
        "shortChannelId": "355x1x0",
        "timestamp": {
            "iso": "2023-08-12T12:16:57Z",
            "unix": 1691842617
        },
        "messageFlags": {
            "dontForward": false
        },
        "channelFlags": {
            "isEnabled": true,
            "isNode1": false
        },
        "cltvExpiryDelta": 144,
        "htlcMinimumMsat": 1,
        "feeBaseMsat": 7856,
        "feeProportionalMillionths": 5679,
        "htlcMaximumMsat": 45000000,
        "tlvStream": {
        }
    },
    {
        "signature": "ef4bfb3a17f1891bb468bb9372bbc95f99055af47ce65e2cb8a79f471d1f202a5719b36fd68d040639117936040f3cc52404cfbe2b24848756a6efe69171d87c",
        "chainHash": "06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f",
        "shortChannelId": "458x2x0",
        "timestamp": {
            "iso": "2023-08-12T12:16:57Z",
            "unix": 1691842617
        },
        "messageFlags": {
            "dontForward": false
        },
        "channelFlags": {
            "isEnabled": true,
            "isNode1": false
        },
        "cltvExpiryDelta": 144,
        "htlcMinimumMsat": 1,
        "feeBaseMsat": 7856,
        "feeProportionalMillionths": 5679,
        "htlcMaximumMsat": 45000000,
        "tlvStream": {
        }
    },
    {
        "signature": "54a1c7c5945b1dcfa1894997d468ffa52ffc1c391a9d10b7744fceae4752d7261177b669791d0a6623cd06344ae61c816ade120850afc318a785b619f45697d6",
        "chainHash": "06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f",
        "shortChannelId": "458x3x0",
        "timestamp": {
            "iso": "2023-08-12T12:16:57Z",
            "unix": 1691842617
        },
        "messageFlags": {
            "dontForward": false
        },
        "channelFlags": {
            "isEnabled": true,
            "isNode1": false
        },
        "cltvExpiryDelta": 144,
        "htlcMinimumMsat": 1,
        "feeBaseMsat": 7856,
        "feeProportionalMillionths": 5679,
        "htlcMaximumMsat": 45000000,
        "tlvStream": {
        }
    }
]
```

**Review by t-bast — COMMENTED** [review]
LGTM once rebased :+1:

**Review by t-bast — APPROVED** [review]

**Pull request merged**
